version: '3'
services:

  #php service
  backend:
    build:
      args:
          user: www
          uid: 1000
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: web-fusa
    env_file:
      - ./backend/.env
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - SERVICE_NAME=web-fusa
      - SERVICE_TAGS=prod
    networks:
      - fusa-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver-fusa
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./backend/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - fusa-network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    container_name: front_fusa
    volumes:
       - ./front:/app
       - ./front/node_modules:/app/node_modules
    networks:
      - fusa-network

#Docker Networks
networks:
  fusa-network:
    driver: bridge

#Volumes
volumes:
  pgdata-fusa-prod:
    driver: local