# Base image
FROM node:18.14.1-alpine as frontend

RUN mkdir /app
WORKDIR /app
COPY package.json package-lock.json /app/
COPY . .
RUN npm install
RUN npm run build


# nginx serve
FROM nginxinc/nginx-unprivileged 
USER root
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend /app/build/ /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 