# Base image
FROM node:18.14.1-alpine as frontend

RUN mkdir /app
WORKDIR /app
COPY package.json package-lock.json /app/
RUN npm install
COPY . .
RUN npm install -g create-vite
EXPOSE 5173
CMD ["npm", "run", "dev"]